# Generated by Django 3.2.4 on 2021-06-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercustomer',
            name='dob',
        ),
    ]
