# Generated by Django 3.2.4 on 2021-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_registercustomer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercustomer',
            name='dob',
            field=models.DateField(default='1991-01-01', max_length=10),
            preserve_default=False,
        ),
    ]
