# Generated by Django 3.2.4 on 2021-07-01 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0003_registercustomer_dob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterCustomer',
            new_name='Customer',
        ),
    ]
