# Generated by Django 3.2.5 on 2021-07-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210722_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessowner',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='businessowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registercustomer',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='registercustomer',
            name='WinCoins',
        ),
        migrations.AddField(
            model_name='businessowner',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='businessowner',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
