# Generated by Django 3.2.4 on 2021-07-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210724_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercustomer',
            name='placesVisited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registercustomer',
            name='winCoins',
            field=models.IntegerField(default=50),
        ),
    ]
