# Generated by Django 3.2.4 on 2021-07-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20210726_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercustomer',
            name='vouchers',
            field=models.IntegerField(default=0),
        ),
    ]
